package com.example.demo.model;

public class Alert {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..alert.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..alert.uid
	 * @mbg.generated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..alert.state
	 * @mbg.generated
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..alert.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..alert.id
	 * @return  the value of cAuth..alert.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..alert.id
	 * @param id  the value for cAuth..alert.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..alert.uid
	 * @return  the value of cAuth..alert.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..alert.uid
	 * @param uid  the value for cAuth..alert.uid
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..alert.state
	 * @return  the value of cAuth..alert.state
	 * @mbg.generated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..alert.state
	 * @param state  the value for cAuth..alert.state
	 * @mbg.generated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..alert.content
	 * @return  the value of cAuth..alert.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..alert.content
	 * @param content  the value for cAuth..alert.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}