package com.example.demo.model;

public class Location {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..location.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..location.uid
	 * @mbg.generated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..location.lat
	 * @mbg.generated
	 */
	private Double lat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..location.lng
	 * @mbg.generated
	 */
	private Double lng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..location.addr
	 * @mbg.generated
	 */
	private String addr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..location.id
	 * @return  the value of cAuth..location.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..location.id
	 * @param id  the value for cAuth..location.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..location.uid
	 * @return  the value of cAuth..location.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..location.uid
	 * @param uid  the value for cAuth..location.uid
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..location.lat
	 * @return  the value of cAuth..location.lat
	 * @mbg.generated
	 */
	public Double getLat() {
		return lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..location.lat
	 * @param lat  the value for cAuth..location.lat
	 * @mbg.generated
	 */
	public void setLat(Double lat) {
		this.lat = lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..location.lng
	 * @return  the value of cAuth..location.lng
	 * @mbg.generated
	 */
	public Double getLng() {
		return lng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..location.lng
	 * @param lng  the value for cAuth..location.lng
	 * @mbg.generated
	 */
	public void setLng(Double lng) {
		this.lng = lng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..location.addr
	 * @return  the value of cAuth..location.addr
	 * @mbg.generated
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..location.addr
	 * @param addr  the value for cAuth..location.addr
	 * @mbg.generated
	 */
	public void setAddr(String addr) {
		this.addr = addr == null ? null : addr.trim();
	}
}