package com.example.demo.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.type
	 * @mbg.generated
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.bid
	 * @mbg.generated
	 */
	private Integer bid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.user
	 * @mbg.generated
	 */
	private String user;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.mphone
	 * @mbg.generated
	 */
	private String mphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.birthday
	 * @mbg.generated
	 */
	private String birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.sex
	 * @mbg.generated
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cAuth..user.imgUrl
	 * @mbg.generated
	 */
	private String imgUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.id
	 * @return  the value of cAuth..user.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.id
	 * @param id  the value for cAuth..user.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.type
	 * @return  the value of cAuth..user.type
	 * @mbg.generated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.type
	 * @param type  the value for cAuth..user.type
	 * @mbg.generated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.bid
	 * @return  the value of cAuth..user.bid
	 * @mbg.generated
	 */
	public Integer getBid() {
		return bid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.bid
	 * @param bid  the value for cAuth..user.bid
	 * @mbg.generated
	 */
	public void setBid(Integer bid) {
		this.bid = bid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.user
	 * @return  the value of cAuth..user.user
	 * @mbg.generated
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.user
	 * @param user  the value for cAuth..user.user
	 * @mbg.generated
	 */
	public void setUser(String user) {
		this.user = user == null ? null : user.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.password
	 * @return  the value of cAuth..user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.password
	 * @param password  the value for cAuth..user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.mphone
	 * @return  the value of cAuth..user.mphone
	 * @mbg.generated
	 */
	public String getMphone() {
		return mphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.mphone
	 * @param mphone  the value for cAuth..user.mphone
	 * @mbg.generated
	 */
	public void setMphone(String mphone) {
		this.mphone = mphone == null ? null : mphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.name
	 * @return  the value of cAuth..user.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.name
	 * @param name  the value for cAuth..user.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.birthday
	 * @return  the value of cAuth..user.birthday
	 * @mbg.generated
	 */
	public String getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.birthday
	 * @param birthday  the value for cAuth..user.birthday
	 * @mbg.generated
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday == null ? null : birthday.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.sex
	 * @return  the value of cAuth..user.sex
	 * @mbg.generated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.sex
	 * @param sex  the value for cAuth..user.sex
	 * @mbg.generated
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cAuth..user.imgUrl
	 * @return  the value of cAuth..user.imgUrl
	 * @mbg.generated
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cAuth..user.imgUrl
	 * @param imgUrl  the value for cAuth..user.imgUrl
	 * @mbg.generated
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl == null ? null : imgUrl.trim();
	}
}