package com.example.demo.mapper;

import com.example.demo.model.Alert;
import com.example.demo.model.AlertExample;
import com.example.demo.pojo.AlertList;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlertMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	long countByExample(AlertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	int deleteByExample(AlertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	int insert(Alert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	int insertSelective(Alert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	List<Alert> selectByExample(AlertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	Alert selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Alert record, @Param("example") AlertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Alert record, @Param("example") AlertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Alert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..alert
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Alert record);

	List<AlertList> selectAlertList(@Param("bid") int bid);
}