package com.example.demo.mapper;

import com.example.demo.model.Location;
import com.example.demo.model.LocationExample;
import com.example.demo.pojo.OlderLocation;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	long countByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	int deleteByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	int insert(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	int insertSelective(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	List<Location> selectByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	Location selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Location record, @Param("example") LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cAuth..location
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Location record);
	
	List<OlderLocation> getLocation(@Param("uid") int uid);
}